ce103_hw5_snake_dll.Class1 Class Reference
Public Member Functions
ConsoleKey waitForAnyKey ()
int getGameSpeed ()
void pauseMenu ()
ConsoleKey checkKeysPressed (ConsoleKey destination)
bool collisionSnake (int x, int y, int[,] snakeXY, int snakeLength, int detect)
void generateFood (int[] foodXY, int width, int height, int[,] snakeXY, int snakeLength)
void moveSnakeArray (int[,] snakeXY, int snakeLength, ConsoleKey direction)
 Move Snake Body (move)
Move snake body
Moving snake body
Parameters
 in snakeXY [int[,]] snake coordinates
 in snakeLength [int] index of fibonacci number in the serie
 in direction [ConsoleKey] index of fibonacci number in the serie
void move (int[,] snakeXY, int snakeLength, ConsoleKey direction)
bool eatFood (int[,] snakeXY, int[] foodXY)
bool collisionDetection (int[,] snakeXY, int consoleWidth, int consoleHeight, int snakeLength)
void refreshInfoBar (int score, int speed)
void youWinScreen ()
void gameOverScreen ()
void startGame (int[,] snakeXY, int[] foodXY, int consoleWidth, int consoleHeight, int snakeLength, ConsoleKey destination, int score, int speed)
void loadEnviroment (int consoleWidth, int consoleHeight)
void loadSnake (int[,] snakeXY, int snakeLength)
void prepairSnakeArray (int[,] snakeXY, int snakeLength)
void loadGame ()
int menuSelector (int x, int y, int yStart)
void welcomeArt ()
void controls ()
void exitYN ()
int mainMenu ()
int main ()
Static Public Attributes
const int SNAKE_ARRAY_SIZE = 310
const ConsoleKey UP_ARROW = ConsoleKey.UpArrow
const ConsoleKey LEFT_ARROW = ConsoleKey.LeftArrow
const ConsoleKey RIGHT_ARROW = ConsoleKey.RightArrow
const ConsoleKey DOWN_ARROW = ConsoleKey.DownArrow
const ConsoleKey ENTER_KEY = ConsoleKey.Enter
const ConsoleKey EXIT_BUTTON = ConsoleKey.Escape
const ConsoleKey PAUSE_BUTTON = ConsoleKey.P
Static Private Attributes
const char SNAKE_HEAD = (char)177
const char SNAKE_BODY = (char)178
const char WALL = (char)219
const char FOOD = (char)254
const char BLANK = ' '
Member Function Documentation
checkKeysPressed()
ConsoleKey ce103_hw5_snake_dll.Class1.checkKeysPressed (ConsoleKey destination) [inline]
References ce103_hw5_snake_dll.Class1.DOWN_ARROW, ce103_hw5_snake_dll.Class1.EXIT_BUTTON, ce103_hw5_snake_dll.Class1.LEFT_ARROW, ce103_hw5_snake_dll.Class1.PAUSE_BUTTON, ce103_hw5_snake_dll.Class1.pauseMenu(), ce103_hw5_snake_dll.Class1.RIGHT_ARROW, and ce103_hw5_snake_dll.Class1.UP_ARROW.
Referenced by ce103_hw5_snake_dll.Class1.startGame().
collisionDetection()
bool ce103_hw5_snake_dll.Class1.collisionDetection (int snakeXY[,], int consoleWidth, int consoleHeight, int snakeLength) [inline]
References ce103_hw5_snake_dll.Class1.collisionSnake().
Referenced by ce103_hw5_snake_test.UnitTest1.collisionDetection_test_1(), ce103_hw5_snake_test.UnitTest1.collisionDetection_test_2(), ce103_hw5_snake_test.UnitTest1.collisionDetection_test_3(), ce103_hw5_snake_test.UnitTest1.collisionSnake_test_1(), ce103_hw5_snake_test.UnitTest1.collisionSnake_test_2(), ce103_hw5_snake_test.UnitTest1.collisionSnake_test_3(), and ce103_hw5_snake_dll.Class1.startGame().
collisionSnake()
bool ce103_hw5_snake_dll.Class1.collisionSnake (int x, int y, int snakeXY[,], int snakeLength, int detect) [inline]
Referenced by ce103_hw5_snake_dll.Class1.collisionDetection(), and ce103_hw5_snake_dll.Class1.generateFood().
controls()
void ce103_hw5_snake_dll.Class1.controls () [inline]
Referenced by ce103_hw5_snake_dll.Class1.main(), and ce103_hw5_snake_app.Program.Main().
eatFood()
bool ce103_hw5_snake_dll.Class1.eatFood (int snakeXY[,], int[] foodXY) [inline]
Referenced by ce103_hw5_snake_test.UnitTest1.Eatfood_test_1(), ce103_hw5_snake_test.UnitTest1.Eatfood_test_2(), ce103_hw5_snake_test.UnitTest1.Eatfood_test_3(), and ce103_hw5_snake_dll.Class1.startGame().
exitYN()
void ce103_hw5_snake_dll.Class1.exitYN () [inline]
References ce103_hw5_snake_dll.Class1.waitForAnyKey().
Referenced by ce103_hw5_snake_dll.Class1.main(), and ce103_hw5_snake_app.Program.Main().
gameOverScreen()
void ce103_hw5_snake_dll.Class1.gameOverScreen () [inline]
References ce103_hw5_snake_dll.Class1.waitForAnyKey().
Referenced by ce103_hw5_snake_dll.Class1.startGame().
generateFood()
void ce103_hw5_snake_dll.Class1.generateFood (int[] foodXY, int width, int height, int snakeXY[,], int snakeLength) [inline]
References ce103_hw5_snake_dll.Class1.collisionSnake(), and ce103_hw5_snake_dll.Class1.FOOD.
Referenced by ce103_hw5_snake_dll.Class1.loadGame(), and ce103_hw5_snake_dll.Class1.startGame().
getGameSpeed()
int ce103_hw5_snake_dll.Class1.getGameSpeed () [inline]
Referenced by ce103_hw5_snake_dll.Class1.loadGame().
loadEnviroment()
void ce103_hw5_snake_dll.Class1.loadEnviroment (int consoleWidth, int consoleHeight) [inline]
References ce103_hw5_snake_dll.Class1.WALL.
Referenced by ce103_hw5_snake_dll.Class1.loadGame().
loadGame()
void ce103_hw5_snake_dll.Class1.loadGame () [inline]
References ce103_hw5_snake_dll.Class1.generateFood(), ce103_hw5_snake_dll.Class1.getGameSpeed(), ce103_hw5_snake_dll.Class1.loadEnviroment(), ce103_hw5_snake_dll.Class1.loadSnake(), ce103_hw5_snake_dll.Class1.prepairSnakeArray(), ce103_hw5_snake_dll.Class1.refreshInfoBar(), ce103_hw5_snake_dll.Class1.SNAKE_ARRAY_SIZE, and ce103_hw5_snake_dll.Class1.startGame().
Referenced by ce103_hw5_snake_dll.Class1.main(), and ce103_hw5_snake_app.Program.Main().
loadSnake()
void ce103_hw5_snake_dll.Class1.loadSnake (int snakeXY[,], int snakeLength) [inline]
References ce103_hw5_snake_dll.Class1.SNAKE_BODY.
Referenced by ce103_hw5_snake_dll.Class1.loadGame().
main()
int ce103_hw5_snake_dll.Class1.main () [inline]
References ce103_hw5_snake_dll.Class1.controls(), ce103_hw5_snake_dll.Class1.exitYN(), ce103_hw5_snake_dll.Class1.loadGame(), ce103_hw5_snake_dll.Class1.mainMenu(), and ce103_hw5_snake_dll.Class1.welcomeArt().
mainMenu()
int ce103_hw5_snake_dll.Class1.mainMenu () [inline]
References ce103_hw5_snake_dll.Class1.menuSelector().
Referenced by ce103_hw5_snake_dll.Class1.main(), and ce103_hw5_snake_app.Program.Main().
menuSelector()
int ce103_hw5_snake_dll.Class1.menuSelector (int x, int y, int yStart) [inline]
References ce103_hw5_snake_dll.Class1.DOWN_ARROW, ce103_hw5_snake_dll.Class1.ENTER_KEY, ce103_hw5_snake_dll.Class1.UP_ARROW, and ce103_hw5_snake_dll.Class1.waitForAnyKey().
Referenced by ce103_hw5_snake_dll.Class1.mainMenu().
move()
void ce103_hw5_snake_dll.Class1.move (int snakeXY[,], int snakeLength, ConsoleKey direction) [inline]
References ce103_hw5_snake_dll.Class1.BLANK, ce103_hw5_snake_dll.Class1.moveSnakeArray(), ce103_hw5_snake_dll.Class1.SNAKE_BODY, and ce103_hw5_snake_dll.Class1.SNAKE_HEAD.
Referenced by ce103_hw5_snake_dll.Class1.startGame().
moveSnakeArray()
void ce103_hw5_snake_dll.Class1.moveSnakeArray (int snakeXY[,], int snakeLength, ConsoleKey direction) [inline]
References ce103_hw5_snake_dll.Class1.DOWN_ARROW, ce103_hw5_snake_dll.Class1.LEFT_ARROW, ce103_hw5_snake_dll.Class1.RIGHT_ARROW, and ce103_hw5_snake_dll.Class1.UP_ARROW.
Referenced by ce103_hw5_snake_dll.Class1.move().
pauseMenu()
void ce103_hw5_snake_dll.Class1.pauseMenu () [inline]
References ce103_hw5_snake_dll.Class1.waitForAnyKey().
Referenced by ce103_hw5_snake_dll.Class1.checkKeysPressed().
prepairSnakeArray()
void ce103_hw5_snake_dll.Class1.prepairSnakeArray (int snakeXY[,], int snakeLength) [inline]
Referenced by ce103_hw5_snake_dll.Class1.loadGame().
refreshInfoBar()
void ce103_hw5_snake_dll.Class1.refreshInfoBar (int score, int speed) [inline]
Referenced by ce103_hw5_snake_dll.Class1.loadGame(), and ce103_hw5_snake_dll.Class1.startGame().
startGame()
void ce103_hw5_snake_dll.Class1.startGame (int snakeXY[,], int[] foodXY, int consoleWidth, int consoleHeight, int snakeLength, ConsoleKey destination, int score, int speed) [inline]
References ce103_hw5_snake_dll.Class1.checkKeysPressed(), ce103_hw5_snake_dll.Class1.collisionDetection(), ce103_hw5_snake_dll.Class1.eatFood(), ce103_hw5_snake_dll.Class1.gameOverScreen(), ce103_hw5_snake_dll.Class1.generateFood(), ce103_hw5_snake_dll.Class1.move(), ce103_hw5_snake_dll.Class1.refreshInfoBar(), ce103_hw5_snake_dll.Class1.SNAKE_ARRAY_SIZE, and ce103_hw5_snake_dll.Class1.youWinScreen().
Referenced by ce103_hw5_snake_dll.Class1.loadGame().
waitForAnyKey()
ConsoleKey ce103_hw5_snake_dll.Class1.waitForAnyKey () [inline]
Referenced by ce103_hw5_snake_dll.Class1.exitYN(), ce103_hw5_snake_dll.Class1.gameOverScreen(), ce103_hw5_snake_dll.Class1.menuSelector(), ce103_hw5_snake_dll.Class1.pauseMenu(), ce103_hw5_snake_dll.Class1.welcomeArt(), and ce103_hw5_snake_dll.Class1.youWinScreen().
welcomeArt()
void ce103_hw5_snake_dll.Class1.welcomeArt () [inline]
References ce103_hw5_snake_dll.Class1.waitForAnyKey().
Referenced by ce103_hw5_snake_dll.Class1.main(), and ce103_hw5_snake_app.Program.Main().
youWinScreen()
void ce103_hw5_snake_dll.Class1.youWinScreen () [inline]
References ce103_hw5_snake_dll.Class1.waitForAnyKey().
Referenced by ce103_hw5_snake_dll.Class1.startGame().
Field Documentation
BLANK
const char ce103_hw5_snake_dll.Class1.BLANK = ' ' [static], [private]
Referenced by ce103_hw5_snake_dll.Class1.move().
DOWN_ARROW
const ConsoleKey ce103_hw5_snake_dll.Class1.DOWN_ARROW = ConsoleKey.DownArrow [static]
Referenced by ce103_hw5_snake_dll.Class1.checkKeysPressed(), ce103_hw5_snake_dll.Class1.menuSelector(), and ce103_hw5_snake_dll.Class1.moveSnakeArray().
ENTER_KEY
const ConsoleKey ce103_hw5_snake_dll.Class1.ENTER_KEY = ConsoleKey.Enter [static]
Referenced by ce103_hw5_snake_dll.Class1.menuSelector().
EXIT_BUTTON
const ConsoleKey ce103_hw5_snake_dll.Class1.EXIT_BUTTON = ConsoleKey.Escape [static]
Referenced by ce103_hw5_snake_dll.Class1.checkKeysPressed().
FOOD
const char ce103_hw5_snake_dll.Class1.FOOD = (char)254 [static], [private]
Referenced by ce103_hw5_snake_dll.Class1.generateFood().
LEFT_ARROW
const ConsoleKey ce103_hw5_snake_dll.Class1.LEFT_ARROW = ConsoleKey.LeftArrow [static]
Referenced by ce103_hw5_snake_dll.Class1.checkKeysPressed(), and ce103_hw5_snake_dll.Class1.moveSnakeArray().
PAUSE_BUTTON
const ConsoleKey ce103_hw5_snake_dll.Class1.PAUSE_BUTTON = ConsoleKey.P [static]
Referenced by ce103_hw5_snake_dll.Class1.checkKeysPressed().
RIGHT_ARROW
const ConsoleKey ce103_hw5_snake_dll.Class1.RIGHT_ARROW = ConsoleKey.RightArrow [static]
Referenced by ce103_hw5_snake_dll.Class1.checkKeysPressed(), and ce103_hw5_snake_dll.Class1.moveSnakeArray().
SNAKE_ARRAY_SIZE
const int ce103_hw5_snake_dll.Class1.SNAKE_ARRAY_SIZE = 310 [static]
Referenced by ce103_hw5_snake_dll.Class1.loadGame(), and ce103_hw5_snake_dll.Class1.startGame().
SNAKE_BODY
const char ce103_hw5_snake_dll.Class1.SNAKE_BODY = (char)178 [static], [private]
Referenced by ce103_hw5_snake_dll.Class1.loadSnake(), and ce103_hw5_snake_dll.Class1.move().
SNAKE_HEAD
const char ce103_hw5_snake_dll.Class1.SNAKE_HEAD = (char)177 [static], [private]
Referenced by ce103_hw5_snake_dll.Class1.move().
UP_ARROW
const ConsoleKey ce103_hw5_snake_dll.Class1.UP_ARROW = ConsoleKey.UpArrow [static]
Referenced by ce103_hw5_snake_dll.Class1.checkKeysPressed(), ce103_hw5_snake_dll.Class1.menuSelector(), and ce103_hw5_snake_dll.Class1.moveSnakeArray().
WALL
const char ce103_hw5_snake_dll.Class1.WALL = (char)219 [static], [private]
Referenced by ce103_hw5_snake_dll.Class1.loadEnviroment().
The documentation for this class was generated from the following file:
C:/a/ce103-hw5-omer-polat/ce103-hw5-snake-dll/Class1.cs